### ISSUE TITLE
Publish beta.1 on npm

### ISSUE THREAD

**Issue by colourgarden** [frctl/twig#1]
Hi @allmarkedup. When installing this adapter via npm, the alpha.0 release is installed (`1.0.0-alpha.0 is the latest of 5 releases`) which doesn't work with v1.1.4. When I manually installed beta.1, everything worked fine. Think you just need to publish the npm package to make sure it's updated. Thanks

https://www.npmjs.com/package/@frctl/twig

**Comment by fvsch** [comment]
I think this can be closed, @colourgarden. beta.1 and beta.2 are on npm now.
