### ISSUE TITLE
Properly close #13 with version bump and npm publish

### ISSUE THREAD

**Issue by therealpecus** [frctl/twig#16]
Hi @Chapabu ,

I think we need a version bump and npm publish to ensure the fix for #13 is propagated to the registry. Currently, v. 1.0.0-beta.4 still resolves to https://registry.npmjs.org/@frctl/twig/-/twig-1.0.0-beta.4.tgz which is the broken version.

From `package-lock.json`
```json
    "@frctl/twig": {
      "version": "1.0.0-beta.4",
      "resolved": "https://registry.npmjs.org/@frctl/twig/-/twig-1.0.0-beta.4.tgz",
      "integrity": "sha512-TyP0GOAZQdzYn1Wgy+rfPjFwCWzgWXstRmtMwdBrPFxL4dikPLCShQCralEUCduuini9DQLEsLeUHdeK1F7Cyg==",
      "dev": true,
      "requires": {
        "lodash": "^4.17.10",
        "twig": "^1.12.0"
      }
```

Thanks!

**Comment by Chapabu** [comment]
@dkhuntrods Do we want to think about publishing a `@next` release? I'm apprehensive to make a proper release until the main Fractal release we've got in progress has stabilised. I don't have access to publish to NPM otherwise I'd do it myself :)

**Comment by Chapabu** [comment]
@therealpecus In the interim you should be able to install directly from Github

**Comment by therealpecus** [comment]
Yes, that would do. My concern is mainly so that those who hit the buggy release and are still stuck on it can access the fixed code easily.

**Comment by dkhuntrods** [comment]
@Chapabu, @therealpecus  thanks - yep I'm planning on reviewing and syncing all adapters this weekend as well as getting the fractal core circular ref out under a beta tag, which should resolve a lot of issues

**Comment by dkhuntrods** [comment]
@Chapabu Also I'll look at getting you npm access - I thought you had for some reason! :)

**Comment by dkhuntrods** [comment]
@Chapabu 
@therealpecus 
I've published an @next release: https://www.npmjs.com/package/@frctl/twig/v/1.0.0-beta.5
#13
