### ISSUE TITLE
Migrate "render" helper into real Twig

### ISSUE THREAD

**Issue by julkue** [frctl/twig#23]
I'm using this Twig handler to easily reference templates from within a backend Twig template. Therefore I have to also simulate the `@component` handle and `render` as an alternative to `include`. Is someone of you familiar with a way to achieve this?

**Comment by mihkeleidast** [comment]
we export a map of the component handles and file paths to a json file like this:
```
const map = {};
for (let item of fractal.components.flattenDeep()) {
    map[`@${item.handle.replace('--default', '')}`] = item.relViewPath;
}

return map;
```

and in php (wordpress via timber plugin in our case), we add a custom template loader to `Twig_Loader_Chain`:
```
$fractalLoader = new FractalLoader(PATH_TO_TWIG_FOLDER);
new Twig_Loader_Chain([$fractalLoader]);
```

the loader class itself looks like this:
```
<?php
use Twig_LoaderInterface;

class FractalLoader implements Twig_LoaderInterface {

    protected $patternsPath;

    public function __construct($patternsPath) {
        $this->patternsPath = $patternsPath;
    }

    public function getSource($name) {
        $map = {}; // load the exported json file to variable here
        if ($map) {
            $path = $this->patternsPath . DIRECTORY_SEPARATOR . $map->$name;
            if (file_exists($path)) {
                return file_get_contents($path);
            } else {
                trigger_error(sprintf('Twig template not found: %s', $path), E_USER_WARNING);
            }
        }

        return '';
    }

    public function getCacheKey($name) {
        return md5($name);
    }

    public function isFresh($name, $time) {
        return true;
    }

}
```

we don't use the `render` tag, only `include`, so I do not have the code that would implement the `render` tag in PHP. The Twig docs, however, has some examples how to extend twig: https://twig.symfony.com/doc/2.x/advanced.html. If the render tag should just mimic include in PHP, then it should be possible to just copy the `include` source and register a custom tag.

I hope this helps a little!

**Comment by das-peter** [comment]
We're working on an actual render tag implementation based on a custom tag extending the twig include tag. Firsts tests look promising.

**Comment by das-peter** [comment]
Here we go a fist version is ready for testing: https://packagist.org/packages/candoimage/frctl_twig

**Comment by Chapabu** [comment]
I understand the rationale behind this, but I'm going to close this issue as it feels like it's been resolved by your Composer package.
