### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by maximedaoust** [frctl/twig#26]
![preview](https://user-images.githubusercontent.com/8137924/55513134-fdec8300-5632-11e9-9723-57da3080ed33.png)

I have this error whenever I try to create a new preview layout for a group of components

Here's the scaffolding

```javascript
├── components/
│   ├── 04-pages/
│   │   ├── home/
│   │   ├── _preview.twig
│   │   └── pages.config.js
│   └── _preview.twig
```
and here's the pages.config.js file
```javascript 
// pages.config.js
module.exports = {
  prefix: 'page',
  preview: 'fractal/components/04-pages/_preview.twig',
};
```

**Comment by rgfretes** [comment]
Any nes on this ? I am having the same issue

**Comment by mihkeleidast** [comment]
This can be fixed right now by setting the preview to the handle:
```
// pages.config.js
module.exports = {
  prefix: 'page',
  preview: '@page-preview',
};
```
or not setting the preview key at all:
```
// pages.config.js
module.exports = {
  prefix: 'page',
};
```
In my testing, fractal seems to automatically choose the preview in the collection.

This is actually a bug in core, I'll file a PR with the fix.
