### ISSUE TITLE
_self is undefined in recursive embedded component

### ISSUE THREAD

**Issue by julkue** [frctl/twig#27]
When dumping

```
{{ dump(_self) }}
```
in the main component I'm receiving a lot of information including `_self.title`. However, when including the same component, just with a different variant (e.g. `video--autoplay`) using the `render` helper, then `_self` will only contain 

```
  [lang]=> 
  string(4) "Twig"
  [editorMode]=> 
  string(4) "twig"
  [editorScope]=> 
  string(14) "text.html.twig"
```

in the nested call. So I can e.g. no longer check the variant name.

**Comment by mihkeleidast** [comment]
@julmot if still interested in getting this fixed, could you add some examples of how you're including components so I could reproduce the issue? And what would be the expected result?

**Comment by mihkeleidast** [comment]
Closing since inactive. Feel free to ping/re-open/re-file if an example of this issue surfaces.
