### ISSUE TITLE
render tag does not work with twig.js 1.14.0

### ISSUE THREAD

**Issue by mihkeleidast** [frctl/twig#34]
Currently, when installing `@frctl/twig`, it also installs twig.js 1.14.0. However, with that update, all uses of the `render` tag are broken.

For example, when trying to render this template:
```
<div class="b">
    {% render '@a' %}
</div>
```

rendering fails with an error:
>ERROR RENDERING COMPONENT
TypeError: this.importFile is not a function

(PR incoming)

**Comment by samuelbirch** [comment]
any idea when this will get merged?
