### ISSUE TITLE
collection context overriding component context on component view

### ISSUE THREAD

**Issue by samuelbirch** [frctl/twig#41]
so... I have a component that has its context defined in its config file. When viewing the component it shows as expected.

i've now created a collection page and used the "render" tag to show this component, working as expected.

I've now used "with" on the render tag to override some of the context on this collection page, and this works as expected, now my issue is that when i go back a view the component page it is now showing the context from the collection page, not what is defined in the component config context.

**Comment by mihkeleidast** [comment]
This is probably a bug, but could you provide us with an example repository where we could better reproduce the issue?

**Comment by samuelbirch** [comment]
sure, i'll get one setup

**Comment by samuelbirch** [comment]
i've created a repo here: https://github.com/samuelbirch/frctl-test

once running if you go to modules/heading first then go to Pages/gallerys, then back to modules/heading

**Comment by mihkeleidast** [comment]
can you test #44?

**Comment by samuelbirch** [comment]
yes that works :)
