### ISSUE TITLE
`@component` console log

### ISSUE THREAD

**Issue by delrueba** [frctl/twig#8]
Hi Tnottu

Is there a specific reason for the console.log in the 'Custom loader for `@component` reference handles' ?
adapter.js, line 28

Can we remove this or add a settings option to prevent it?
I feel it really clutters up the console output during the build process.

I'm happy to make a pull request!

Bart

**Comment by daften** [comment]
It would be nice if this would only be triggered on verbose output, now the output is very cluttered.
